#!/usr/bin/env ruby
# original script from
# <http://errtheblog.com/posts/89-huba-huba>
# with edits by mogelbrod <http://github.com/mogelbrod>

require 'fileutils'

IS_WINDOWS = (RUBY_PLATFORM =~ /mingw|mswin/i)

home = File.expand_path('~')
dir = File.dirname(__FILE__)
`cd #{dir}` unless dir == '.'

puts "Create symlinks ..."

Dir['*'].each do |origin|
  next if origin == 'install'
  file = ".#{origin}"

  # Special cases
  file = 'vimfiles' if origin == 'vim' && IS_WINDOWS

  target = File.join(home, file)

  if File.exists?(target)
    puts " - #{file} (#{target}) already exists, skipping."
  else
    res = `ln -s #{File.expand_path origin} #{target}`
    if $?.exitstatus != 0
      puts " ! #{target} could not be linked."
    else
      puts " + #{file} => #{target} has been linked."
    end
  end
end

unless IS_WINDOWS
  puts "Create vim swap directory ..."
  FileUtils.mkdir_p "~/.vim/swap"
  FileUtils.mkdir_p "~/.vim/backup"
end

# git push on commit
puts "Tell git to push on commits ..."
`echo 'git push' > #{dir}/.git/hooks/post-commit`
`chmod 755 #{dir}/.git/hooks/post-commit`

# initialize git submodules
puts "Initialize git submodules ..."
`git submodule init`
`git submodule update`

puts "Update (pull) git submodules ..."
`git submodule foreach git pull origin master`

puts "All done!"
