#!/usr/bin/env ruby
# from http://errtheblog.com/posts/89-huba-huba

home = File.expand_path('~')

Dir['*'].each do |file|
  next if file =~ /install/
  if file =~ /fish|roxterm\.sourceforge\.net|awesome/
    target = File.join(home, ".config/")
  else
    target = File.join(home, ".#{file}")
  end
  
  if File.exists?(target)
    puts " - #{file} (#{target}) already exists, skipping."
  else
    res = `ln -s #{File.expand_path file} #{target}`
    if $?.existatus != 0
      puts " ! #{target} could not be linked."
    else
      puts " + #{target} have been linked to #{file}."
    end
  end
end

# git push on commit
#`echo 'git push' > .git/hooks/post-commit`
#`chmod 755 .git/hooks/post-commit`
